version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
  mongodb:
    image: "mongo:latest"
    ports:
      - "3000:3000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "nullbeta"
      MONGO_INITDB_ROOT_PASSWORD: "JVkB8pQm1tOKdbni"
      MONGO_INITDB_DATABASE: "sepherum"
